"""The single place the system talks to an LLM.

Three guarantees this module makes, in order of importance:

1. **Nothing is ever invented locally.** If the model cannot be reached, or
   cannot produce output matching the requested shape, this raises. There is no
   canned fallback copy anywhere in the system — content that reaches a reviewer
   was generated by the configured model or it does not exist at all.
2. **The response is parsed defensively.** Models wrap JSON in prose, in
   ```json fences, in markdown, with trailing commas, with smart quotes, with
   `//` comments. `extract_json()` handles all of it via a string-aware scanner
   rather than the usual `find("{") … rfind("}")`, which silently mangles any
   response with a brace in its trailing prose.
3. **A malformed response is retried with the error fed back.** Transport
   failures are retried by the provider client (`LLM_MAX_RETRIES`); *shape*
   failures are retried here (`LLM_JSON_ATTEMPTS`) by appending the model's own
   bad output and the specific validation error to the conversation. Most
   schema misses self-correct on the second attempt.

Provider selection is config-only: `LLM_PROVIDER` picks a builder out of
`_PROVIDER_BUILDERS`, and adding a provider means adding one entry there plus
its settings block. See docs/architecture/llm-providers.md.
"""
from __future__ import annotations

import functools
import json
import logging
import re
from dataclasses import dataclass
from typing import Any, Callable, Optional

from config import settings

logger = logging.getLogger(__name__)


# --- errors ------------------------------------------------------------------

class LLMError(RuntimeError):
    """Base for every failure in this module. Callers abort the run on these."""


class LLMConfigurationError(LLMError):
    """The provider is misconfigured — unknown name, or a missing API key."""


class LLMUnavailableError(LLMError):
    """The provider could not be reached, or rejected the request."""


class MalformedResponseError(LLMError):
    """The model replied, but never with JSON matching the requested shape."""


class SchemaError(ValueError):
    """A parsed payload violated its node's schema. Raised by graph/schemas.py.

    Carries a message written to be handed straight back to the model as a
    correction, so phrase them as instructions ("beats must contain exactly 5
    entries"), not as diagnostics ("len(beats) == 3").
    """


# --- provider registry -------------------------------------------------------

@dataclass(frozen=True)
class ProviderConfig:
    """Everything needed to build one provider's client, resolved from settings."""

    name: str
    api_key: str
    model: str
    base_url: Optional[str]
    key_setting: str  # the .env variable name, for error messages


def _provider_configs() -> dict[str, ProviderConfig]:
    """Read provider settings fresh.

    Not cached: tests (and `python -m` entry points that call `load_dotenv`
    late) reload settings, and a cache here would pin the first-seen values.
    """
    return {
        "openai": ProviderConfig(
            "openai", settings.OPENAI_API_KEY, settings.OPENAI_MODEL,
            settings.OPENAI_BASE_URL, "OPENAI_API_KEY",
        ),
        "gemini": ProviderConfig(
            "gemini", settings.GEMINI_API_KEY, settings.GEMINI_MODEL,
            settings.GEMINI_BASE_URL, "GEMINI_API_KEY",
        ),
        "anthropic": ProviderConfig(
            "anthropic", settings.ANTHROPIC_API_KEY, settings.ANTHROPIC_MODEL,
            settings.ANTHROPIC_BASE_URL, "ANTHROPIC_API_KEY",
        ),
    }


def _build_openai(config: ProviderConfig):
    from langchain_openai import ChatOpenAI

    return ChatOpenAI(
        model=config.model,
        api_key=config.api_key,
        base_url=config.base_url,
        max_tokens=settings.LLM_MAX_TOKENS,
        timeout=settings.LLM_TIMEOUT_SECONDS,
        max_retries=settings.LLM_MAX_RETRIES,
    )


def _build_gemini(config: ProviderConfig):
    from langchain_google_genai import ChatGoogleGenerativeAI

    return ChatGoogleGenerativeAI(
        model=config.model,
        google_api_key=config.api_key,
        client_options={"api_endpoint": config.base_url} if config.base_url else None,
        max_output_tokens=settings.LLM_MAX_TOKENS,
        timeout=settings.LLM_TIMEOUT_SECONDS,
        max_retries=settings.LLM_MAX_RETRIES,
    )


def _build_anthropic(config: ProviderConfig):
    from langchain_anthropic import ChatAnthropic

    return ChatAnthropic(
        model=config.model,
        api_key=config.api_key,
        base_url=config.base_url,
        max_tokens=settings.LLM_MAX_TOKENS,
        timeout=settings.LLM_TIMEOUT_SECONDS,
        max_retries=settings.LLM_MAX_RETRIES,
    )


# Adding a provider: add its settings block in config/settings.py, a
# ProviderConfig above, and one builder here. Nothing else in the system
# knows which provider is in use.
_PROVIDER_BUILDERS: dict[str, Callable[[ProviderConfig], Any]] = {
    "openai": _build_openai,
    "gemini": _build_gemini,
    "anthropic": _build_anthropic,
}

SUPPORTED_PROVIDERS = tuple(sorted(_PROVIDER_BUILDERS))

# Values that mean "nobody filled this in". A key matching one of these is
# treated as absent, so the failure names the real problem (key not set)
# instead of surfacing a provider's generic 401 several layers down.
_PLACEHOLDER_MARKERS = ("dummy", "placeholder", "changeme", "your-key", "your_key", "xxx", "todo")


def _is_placeholder(key: str) -> bool:
    lowered = (key or "").strip().lower()
    return not lowered or any(marker in lowered for marker in _PLACEHOLDER_MARKERS)


def active_provider() -> str:
    provider = (settings.LLM_PROVIDER or "").strip().lower()
    if provider not in _PROVIDER_BUILDERS:
        raise LLMConfigurationError(
            f"LLM_PROVIDER is {settings.LLM_PROVIDER!r}; expected one of "
            f"{', '.join(SUPPORTED_PROVIDERS)}. Set it in .env."
        )
    return provider


def active_config() -> ProviderConfig:
    return _provider_configs()[active_provider()]


def active_model_name() -> str:
    """The configured model for the active provider — recorded as provenance."""
    return active_config().model


def check_configuration() -> None:
    """Fail fast, with an actionable message, if no real key is configured.

    Called at worker and UI startup so a missing key is a startup error rather
    than a job that dies eight nodes deep.
    """
    config = active_config()
    if _is_placeholder(config.api_key):
        raise LLMConfigurationError(
            f"{config.key_setting} is not set (LLM_PROVIDER={config.name}). "
            f"Add a real key to .env — the pipeline generates no content without one."
        )


@functools.lru_cache(maxsize=1)
def get_chat_model():
    """Build the active provider's client once per process."""
    check_configuration()
    config = active_config()
    try:
        client = _PROVIDER_BUILDERS[config.name](config)
    except ImportError as exc:
        raise LLMConfigurationError(
            f"LLM_PROVIDER={config.name} needs a package that is not installed: {exc}. "
            f"Run: pip install -r requirements.txt"
        ) from exc
    logger.info("LLM client ready: %s / %s", config.name, config.model)
    return client


def reset_model_cache() -> None:
    """Drop the cached client. For tests, and for reconfiguring in-process."""
    get_chat_model.cache_clear()


# --- response text extraction ------------------------------------------------

_FENCE_RE = re.compile(r"```(?:json|JSON)?\s*\n?(.*?)```", re.DOTALL)
# Zero-width and bidi/non-breaking characters: models emit them around fences,
# and they make an otherwise-valid document fail to parse. Written as escapes
# because the literal glyphs are invisible in an editor.
_INVISIBLE_RE = re.compile("[\u200b-\u200f\u202a-\u202e\u2060\ufeff\u00a0]")
_SMART_QUOTES = {
    "“": '"', "”": '"', "„": '"', "″": '"',
    "‘": "'", "’": "'", "‚": "'",
}


def response_text(content: Any) -> str:
    """Flatten a LangChain message payload to plain text.

    Providers return either a string or a list of content blocks; reasoning
    models interleave `thinking` blocks with `text` ones, and concatenating
    everything would drop the model's chain of thought straight into the JSON
    parser. Only `text` blocks are kept.
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: list[str] = []
        for block in content:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict) and block.get("type") == "text":
                parts.append(str(block.get("text", "")))
        return "".join(parts)
    return str(content or "")


def _strip_wrappers(text: str) -> str:
    """Normalize whitespace/invisibles and unwrap a markdown code fence."""
    candidate = _INVISIBLE_RE.sub("", text or "").strip()
    fenced = _FENCE_RE.search(candidate)
    if fenced:
        candidate = fenced.group(1).strip()
    return candidate


def _first_json_object(text: str) -> Optional[str]:
    """Slice out the first complete, brace-balanced JSON object.

    The naive `text[find("{"):rfind("}")+1]` breaks two common real responses:
    an object followed by prose containing a brace (it swallows the prose), and
    two objects in a row (it merges them into invalid JSON). Scanning with
    string/escape awareness is only a few more lines and is always correct.
    """
    start = text.find("{")
    if start == -1:
        return None

    depth = 0
    in_string = False
    escaped = False
    for index in range(start, len(text)):
        char = text[index]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start : index + 1]
    return None


def _repair_json(text: str) -> str:
    """Remove the JSON-invalid habits models fall into, outside of strings.

    Handles `//` and `/* */` comments and trailing commas before `}`/`]`.
    Walks the text tracking string state so a URL's `//`, an apostrophe, or a
    comma inside a value is never touched.

    Smart quotes are deliberately *not* handled here — see `_straighten_quotes`.
    """
    out: list[str] = []
    in_string = False
    escaped = False
    index = 0
    length = len(text)

    while index < length:
        char = text[index]

        if in_string:
            out.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            index += 1
            continue

        if char == '"':
            in_string = True
            out.append(char)
            index += 1
            continue

        if char == "/" and index + 1 < length:
            following = text[index + 1]
            if following == "/":
                index = text.find("\n", index)
                if index == -1:
                    break
                continue
            if following == "*":
                end = text.find("*/", index + 2)
                index = length if end == -1 else end + 2
                continue

        if char == ",":
            # Look ahead past whitespace: a comma before a closer is trailing.
            probe = index + 1
            while probe < length and text[probe] in " \t\r\n":
                probe += 1
            if probe < length and text[probe] in "}]":
                index += 1
                continue

        out.append(char)
        index += 1

    return "".join(out)


def _straighten_quotes(text: str) -> str:
    """Replace every curly quote with its ASCII form.

    A last resort, run only once the document has already failed to parse. It
    can't be part of the normal repair pass: a model that writes `"the “best”
    option"` is using curly quotes as *content*, and rewriting those would
    corrupt perfectly good copy. Once the document is unparseable anyway, the
    likeliest explanation is that they were used as delimiters, and mangling a
    quotation mark beats failing the node.
    """
    return "".join(_SMART_QUOTES.get(char, char) for char in text)


def extract_json(text: str) -> dict[str, Any]:
    """Parse a JSON object out of a raw model response.

    Raises `SchemaError` (not a parse error) so the caller's repair-retry path
    treats an unparseable response exactly like a schema violation — both are
    "the model's output was the wrong shape", and both are fixed the same way.
    """
    candidate = _strip_wrappers(text)
    if not candidate:
        raise SchemaError("the response was empty; reply with a single JSON object")

    sliced = _first_json_object(candidate)
    if sliced is None:
        preview = candidate[:200].replace("\n", " ")
        raise SchemaError(
            f"no JSON object found in the response (it began: {preview!r}); "
            f"reply with a single JSON object and nothing else"
        )

    # Cheapest first: as-is, then comment/trailing-comma repair, then the
    # destructive quote pass only if the document is otherwise unparseable.
    attempts = (sliced, _repair_json(sliced), _repair_json(_straighten_quotes(sliced)))
    for attempt in attempts:
        try:
            parsed = json.loads(attempt, strict=False)
        except json.JSONDecodeError as exc:
            error = exc
            continue
        if isinstance(parsed, dict):
            return parsed
        # A single-element array wrapping the object is a common near-miss.
        if isinstance(parsed, list) and len(parsed) == 1 and isinstance(parsed[0], dict):
            return parsed[0]
        raise SchemaError(
            f"expected a JSON object, got {type(parsed).__name__}; "
            f"reply with a single JSON object"
        )

    raise SchemaError(f"the response was not valid JSON ({error.msg} at line {error.lineno})")


# --- generation --------------------------------------------------------------

@dataclass(frozen=True)
class LLMResult:
    """One successful generation, with the provenance `finalize` records."""

    payload: dict[str, Any]
    provider: str
    model: str
    attempts: int
    repairs: tuple[str, ...] = ()   # schema errors survived on earlier attempts


_REPAIR_TEMPLATE = (
    "Your previous reply could not be used: {error}\n\n"
    "Reply again with the corrected JSON object only. No prose, no markdown "
    "fence, no explanation — just the object, with every required key present "
    "and correctly typed."
)


def generate_json(
    *,
    node: str,
    system: str,
    user: str,
    validator: Callable[[dict[str, Any]], dict[str, Any]],
) -> LLMResult:
    """Ask the configured model for a JSON object and return it validated.

    `validator` takes the parsed payload and returns a normalized version of
    it, raising `SchemaError` with a correctable message if the shape is wrong
    (see graph/schemas.py). Normalization happens there too, so trivially
    fixable output — a hashtag missing its `#`, an out-of-range image index —
    costs no extra round trip.

    Raises `LLMUnavailableError` if the provider cannot be reached, or
    `MalformedResponseError` if it never returned a usable shape. It never
    returns placeholder content.
    """
    from langchain_core.messages import AIMessage, HumanMessage, SystemMessage

    model = get_chat_model()
    config = active_config()
    messages: list[Any] = [SystemMessage(content=system), HumanMessage(content=user)]
    repairs: list[str] = []

    for attempt in range(1, settings.LLM_JSON_ATTEMPTS + 1):
        try:
            response = model.invoke(messages)
        except Exception as exc:  # noqa: BLE001 — every provider raises its own types
            raise LLMUnavailableError(
                f"{node}: {config.name} ({config.model}) call failed: "
                f"{type(exc).__name__}: {exc}"
            ) from exc

        raw = response_text(getattr(response, "content", response))
        logger.info(
            "%s: attempt %d/%d raw response:\n%s",
            node, attempt, settings.LLM_JSON_ATTEMPTS, raw,
        )

        try:
            payload = validator(extract_json(raw))
        except SchemaError as exc:
            repairs.append(str(exc))
            if attempt == settings.LLM_JSON_ATTEMPTS:
                logger.warning(
                    "%s: attempt %d/%d produced an unusable response (%s); no attempts left, giving up",
                    node, attempt, settings.LLM_JSON_ATTEMPTS, exc,
                )
                break
            logger.warning(
                "%s: attempt %d/%d produced an unusable response (%s); retrying with the error fed back",
                node, attempt, settings.LLM_JSON_ATTEMPTS, exc,
            )
            messages.append(AIMessage(content=raw[:4000]))
            messages.append(HumanMessage(content=_REPAIR_TEMPLATE.format(error=exc)))
            continue

        if attempt > 1:
            logger.info("%s: recovered on attempt %d", node, attempt)
        logger.info("%s: generated via %s (%s)", node, config.model, config.name)
        return LLMResult(
            payload=payload,
            provider=config.name,
            model=config.model,
            attempts=attempt,
            repairs=tuple(repairs),
        )

    raise MalformedResponseError(
        f"{node}: {config.name} ({config.model}) did not return a usable response after "
        f"{settings.LLM_JSON_ATTEMPTS} attempts. Last error: {repairs[-1] if repairs else 'unknown'}"
    )
